### ISSUE TITLE
zh-Hans.Iproj

### ISSUE THREAD

**Issue by williambj1** [headkaze/Hackintool#1]
Hi! @headkaze 
I'm so glad that this channel is finally ready!
I'll update the files to the latest version, and make a PR soon.
Could you please initialize this repo?

Cheers!
Bat.bat

**Comment by headkaze** [comment]
Pleade hold out for a bit until I get the latest files committed.

**Comment by headkaze** [comment]
Ready to go

**Comment by williambj1** [comment]
Thanks!
