### ISSUE TITLE
The new added tooltips localization doesn't function etc.

### ISSUE THREAD

**Issue by williambj1** [headkaze/Hackintool#10]
@headkaze 
Hi!
### The new added tooltips localization doesn't function.
I've already translated all of them and I replaced localizable.strings into the current version, but it failed to function.

### Missing localization
![image](https://user-images.githubusercontent.com/45396585/57451305-7e864b00-7293-11e9-8861-4eaf009fe7c8.png)

Cheers!

**Comment by headkaze** [comment]
Can you do a pull request of your changes and I'll take a look. I'll probably need to do a new release.

**Comment by williambj1** [comment]
Sure, what a second and I'll check some typos.

**Comment by headkaze** [comment]
I had to fix some of the \r (carriage return) characters as they had a space between them. Please check out the latest release (2.4.7).

**Comment by williambj1** [comment]
Awesome!  Sorry that I didn't notice the space is necessary. Thanks!
