### ISSUE TITLE
[BUG] "Get AppleIntelInfo" not working with SIP enabled

### ISSUE THREAD

**Issue by dreamwhite** [headkaze/Hackintool#102]
Hi there,
I notice that with fully enabled SIP, AppleIntelInfo kext can't be loaded (for certificate reasons I think).
The obvious consequence of this statement is that Hackintool produces a blank output.
![iTerm](https://user-images.githubusercontent.com/17933708/89706677-407d4880-d968-11ea-8384-ea89748d01e1.png)

![image](https://user-images.githubusercontent.com/17933708/89706684-4f63fb00-d968-11ea-86fd-1b921fba2a8f.png)

What can it be? Do I have to fully disable SIP (or simply allowing loading of unsigned kexts)? If yes, it might be useful checking the SIP status before injecting the kext and displaying an error message if the SIP status can't make the loading of the kext.
Please let me know
Have a nice day

**Comment by 1alessandro1** [comment]
Bump! @headkaze
