### ISSUE TITLE
New acidanthera kext builds need MacKernelSDK

### ISSUE THREAD

**Issue by ganthore** [headkaze/Hackintool#111]
I have a pre-existing and new system that are both suddenly failing to build the acidanthera kexts. I suspect that the developer has changed the build process in some way.

To re-produce, try to build the "latest" Lilu extension from the Extensions menu. Version 1.4.8 worked fine but 1.4.9 will fail. The compiler will complain:

`fatal error: 'libkern/libkern.h' file not found`

After reading through all of their commits between version 1.4.8 -> 1.4.9, it would appear that they have introduced a new build dependency requirement.
https://github.com/acidanthera/Lilu/commit/602b7b04243d482835ab6ff7fd50ab1d3f3c3157

So this SDK needs to be part of the build chain moving forward:
https://github.com/acidanthera/MacKernelSDK

[build.log](https://github.com/headkaze/Hackintool/files/5356602/build.log)

**Comment by headkaze** [comment]
Fixed in [3.4.6](https://github.com/headkaze/Hackintool/releases/tag/3.4.6)
