### ISSUE TITLE
Compilation is only successful for Build DisplayMergeNub

### ISSUE THREAD

**Issue by startergo** [headkaze/Hackintool#114]
![image](https://user-images.githubusercontent.com/7897244/99325797-0ebc2d80-2845-11eb-91f4-86452697e0e0.png)
Hackintool does not build. What should I change?

**Comment by headkaze** [comment]
What's the error you're getting?

**Comment by startergo** [comment]
No error only warnings, but does not build the Hackintool. As you can see in the left bottom corner in red.
There are 2 targets:
![image](https://user-images.githubusercontent.com/7897244/99327257-8428fd80-2847-11eb-892c-81dd6f564d84.png)

**Comment by startergo** [comment]
The reason I am trying to build is that it refuses to open in BigSur. The app gets unresponsive and I have to kill it. Ioregistryexplorer (Native Apple App) has the same behavior.

**Comment by headkaze** [comment]
You need to set your build target.
<img width="400" alt="Screen Shot 2020-11-16 at 8 15 58 PM" src="https://user-images.githubusercontent.com/1698401/99327779-a96a3b80-2848-11eb-81d4-bd61676c2c76.png">

**Comment by startergo** [comment]
I compiled it in Catalina and Big Sur. If I open the app compiled in Catalina on Big Sur it just hangs with "Application not responding" The one compiled in Big Sur does not even open. I wonder if it is some Apple restriction due to applications "calling" home to check the certificate.
