### ISSUE TITLE
I've Prepared New Appicon or you please check it and update it for macOS Big Sur

### ISSUE THREAD

**Issue by singhalrishi27** [headkaze/Hackintool#116]
[AppIcon.appiconset.zip](https://github.com/headkaze/Hackintool/files/5558157/AppIcon.appiconset.zip)

New Appicon For macOS Big Sur
![Icon-1024](https://user-images.githubusercontent.com/67616808/99493055-919fce00-2994-11eb-8578-969590770186.png)

**Comment by headkaze** [comment]
Thanks @singhalrishi27 I ended up making a similar one using a Photoshop template I found.
