### ISSUE TITLE
USB ports

### ISSUE THREAD

**Issue by viorel78** [headkaze/Hackintool#126]
v 3.5.2 shows non-existent USB ports and location ID. 
![Screenshot 2021-01-19 at 14 01 42](https://user-images.githubusercontent.com/64503160/105059960-85adb680-5a80-11eb-9fd0-9a6012c6d565.png)

**Comment by headkaze** [comment]
Try selecting Clear All then Refresh.

**Comment by viorel78** [comment]
> Try selecting Clear All then Refresh.


Clear аll then refresh does not help.
Uninstalled the new version and installed the old 3.4.3 - 
![Uploading Screenshot 2021-01-19 at 21.06.05.png…]()
in this version it normally displays

**Comment by viorel78** [comment]
The latest version which shows correctly is 3.4.9

**Comment by headkaze** [comment]
Please try 3.5.3

**Comment by viorel78** [comment]
3.5.3 shows correctly, thanks.
