### ISSUE TITLE
Extensions section

### ISSUE THREAD

**Issue by Baio1977** [headkaze/Hackintool#127]
I have a problem with the analysis of the kext contained in EFI\OC\Kext.
BrightnessKeys is not recognized

![Schermata 2021-02-06 alle 18 08 47](https://user-images.githubusercontent.com/59058746/107124905-baa27180-68a6-11eb-82df-7c2257d22fc7.png)

**Comment by headkaze** [comment]
Feel free to add it to [kexts.plist](https://github.com/headkaze/Hackintool/blob/master/Resources/Kexts/kexts.plist) and make a pull request.
