### ISSUE TITLE
Extension is red but no update available. Instead it says "Replaced by..." what do I do next?

### ISSUE THREAD

**Issue by cyberfunk** [headkaze/Hackintool#129]
When I run the extension updater it lists two of my kexts in red as needing an update. There are no updates but it says each was replaced by a kext that I already have installed (and updated). Do I delete these kexts in red since they are redundant or will it break my system?

**Comment by feartech** [comment]
> When I run the extension updater it lists two of my kexts in red as needing an update. There are no updates but it says each was replaced by a kext that I already have installed (and updated). Do I delete these kexts in red since they are redundant or will it break my system?

which kexts?
