### ISSUE TITLE
NVRAM tab in Big Sur 11.3 shows preferred-count value as ???

### ISSUE THREAD

**Issue by perez987** [headkaze/Hackintool#130]
First, congratulations and thanks for your excellent work, this app is a must-have in hackintosh world.
The NVRAM tab shows preferred-count variable with a value of ??? although with the "nvram -p" command this variable has a numeric value  according with the number of preferred wifi networks.
Regards, Emilio.

**Comment by headkaze** [comment]
Can you please try 3.5.5

**Comment by perez987** [comment]
Perfect!!! Fixed. Thanks.
