### ISSUE TITLE
Varius BUG V 3.5.3

### ISSUE THREAD

**Issue by Baio1977** [headkaze/Hackintool#131]
Patch : 
This click NO work

![Schermata 2021-05-10 alle 08 02 26](https://user-images.githubusercontent.com/59058746/117612782-101c4200-b166-11eb-93db-4ed86ee1bd02.png)

Patch section Patch :does not generate any patches if added tick on EDID
![Schermata 2021-05-10 alle 08 04 34](https://user-images.githubusercontent.com/59058746/117612958-5d98af00-b166-11eb-9c5c-c23f8b3e7356.png)

USB:it would be good to align to the repositi USBInjectALL  https://github.com/daliansky/OS-X-USB-Inject-All , this repo for serie 500 and varius fix 

Thanks for all

**Comment by headkaze** [comment]
Can you run it from Terminal and see if there's any error output when you click on the 'Generate Patch' button.

**Comment by Baio1977** [comment]
This is output
[Output Hackintool 3.5.3.zip](https://github.com/headkaze/Hackintool/files/6487763/Output.Hackintool.3.5.3.zip)

**Comment by headkaze** [comment]
Can you please try 3.5.5

**Comment by Baio1977** [comment]
> Can you please try 3.5.5


https://user-images.githubusercontent.com/59058746/118404519-8c85b800-b673-11eb-8801-d6254ea2a696.mov

This no work , thanks for all
![Schermata 2021-05-16 alle 18 22 18](https://user-images.githubusercontent.com/59058746/118404540-a7582c80-b673-11eb-997f-8e209a2df2bc.png)

**Comment by headkaze** [comment]
Can you please try 3.5.6

**Comment by Baio1977** [comment]
> Can you please try 3.5.6
The button bug has been fixed with V3.5.6 ,
thank you for giving us this great application.
I will try to add the graphic patches that I gradually manage to make and I will notify you of the changes.
I have a question  :
is it possible to put Desktop folder and Notebook folder with the relative subfolders of the various manufacturers ???
Thank you
