### ISSUE TITLE
AirportItlwm.kext not detected again in Hackintool 3.6.0

### ISSUE THREAD

**Issue by mackonsti** [headkaze/Hackintool#139]
Hello @headkaze hope you are well and safe. Thanks for the update of this great tool to 3.6.0.

Unfortunately on BigSur, the **AirportItlwm.kext** kext is again **not** detected in the Extensions list, despite being loaded OK on the system. When updated to Hackintool 3.6.0 and saw that the kext was missing, I was under the impression that I had done something wrong in my OpenCore config but `kextstat` does show it loaded.

I believe it has possibly again to do with the Info.plist you load with all those extensions and descriptions etc. I will see if I can find the issue to help you if you don't have time to investigate. But the problem remains for your latest release.

Thank you.

**Comment by williambj1** [comment]
https://github.com/headkaze/Hackintool/pull/132/files#diff-d07bb57395ad95e9c877e6bf33b16f86cb99f60dccc0d6b56f5eb8a51712c6c5L570-L579

Not sure why it was replaced by `BrightnessKeys` in this PR.

**Comment by headkaze** [comment]
I'm guessing it was deleted because there's another entry for the same kext in there. Looking at the bundle names it looks like there's two depending on different macOS versions.

```
MACOSX_DEPLOYMENT_TARGET = 10.9;
MODULE_NAME = com.zxystd.itlwm;
PRODUCT_BUNDLE_IDENTIFIER = com.zxystd.itlwm;
```

```
	<dict>
		<key>Name</key>
		<string>itlwm</string>
		<key>BundleID</key>
		<string>itlwm</string>
		<key>Description</key>
		<string>An OpenBSD-based macOS Intel wireless card driver for supported devices that behaves as an Ethernet card; must be accompanied by HeliPort.app to control it</string>
		<key>ProjectUrl</key>
		<string>https://github.com/OpenIntelWireless/itlwm</string>
		<key>Type</key>
		<string>Kext</string>
	</dict>
```

```
MACOSX_DEPLOYMENT_TARGET = 10.15;
MODULE_NAME = com.zxystd.AirportItlwm;
PRODUCT_BUNDLE_IDENTIFIER = com.zxystd.AirportItlwm;
```

```
	<dict>
		<key>Name</key>
		<string>itlwm</string>
		<key>BundleID</key>
		<string>AirportItlwm</string>
		<key>Description</key>
		<string>An OpenBSD-based macOS Intel wireless card driver for supported devices that behaves like an integrated AirPort card</string>
		<key>ProjectUrl</key>
		<string>https://github.com/OpenIntelWireless/itlwm</string>
		<key>Type</key>
		<string>Kext</string>
	</dict>
```

I've added back the second entry. Please try 3.6.1

**Comment by mackonsti** [comment]
Hi @headkaze thanks for your quick response!

As you may recakk, the developer is releasing 2 different kexts under the same name; one kext is acting as a LAN driver and needs a tool to activate the Intel Wireless device, the other tool is an actual WLAN driver that integrates seamlessly with the macOS.

Your fix seems to correct things, after updating Hackingtool are refreshing online data (version info):

On my Intel NUC (Catalina) using the "LAN" driver, the versioning shows OK as 1.3.0 👍 
On my other Intel NUC (Big Sur) using the true "WLAN" driver, the versioning shows as 1.3.0 👍 too

Thank you!
