### ISSUE TITLE
@headkaze i've got an idea one more thing~!

### ISSUE THREAD

**Issue by ZISQO** [headkaze/Hackintool#14]
I have a command to enable AMD's graphics for hardware acceleration (RX480/RX580/VEGA),
and what if you want to run it with one click on the Hackintool?

**Comment by headkaze** [comment]
What's the command?

**Comment by ZISQO** [comment]
shell command~ :)

**Comment by ZISQO** [comment]
i know how to enable AMD hardware acceleration shell command without shiki and that's working fine quicksync and VEGA RX 64 , VEGA FE 64 in Finalcut, Davinci Resolve, Premiere...
i wish support one click patch on Hackintool how about you?

**Comment by vit9696** [comment]
Sorry, but enabling AMD acceleration (or in fact any other) is done by the correct choice of mac model. Even without the details provided, I am afraid what you are talking about implies inducing permanent harm to operating system core files.

Vit

**Comment by headkaze** [comment]
I won't be including any scripts or tools that patch core system files in Hackintool.

**Comment by ZISQO** [comment]
yo yo yo~ don't be afraid my mean was right this.
basically AMD card are not enabled H264 & H265 encoding in FCPX and Davinci Resolve, Premiere without drm patch (in terminal).

1. VEGA RX 64 / FE : 264 works  but 265(HEVC) are working with Software Encoding
2. RX 4xx seriese and RX 5xx seriese : h264, h264 are working with Software Encoding
3. both cards are freezing when encoding without drm patch

this is no need to afraid because of this drm patch are working good such a shiki.kext
(but also shiki.kext are not worked from mojave cus i'm using manual drm patch on terminal when clean install)

so many korean users using this DRM patch on terminal. no problem when encoding on davinci, fcpx, premiere with h264, h265, Prores codecs. it not on gaming  hhh : )

i know my first time storie are heard like for gaming acceleration...

**Comment by Andrey1970AppleLife** [comment]
The functionality Shiki is in WEG.kext

**Comment by ZISQO** [comment]
but shiki is not working on 10.4.x

**Comment by Andrey1970AppleLife** [comment]
Works at 10.14.х but if you have problems, write in Acidanthera Bugtracker.

**Comment by ZISQO** [comment]
today i was build up the DRM setup & reset for AMD seriese with xcode by myself
actually shikivga are won't work alone before DRM setting..

ex)
forceATI active, hardwareVideoDecoder active, forceSWDecoder deactive
if without this work with iMacPro1,1 are Keep freezing when h264, h265 encoding on Davinci resolve, Finalcut Pro X, Adobe Premiere : )

https://i.imgur.com/u17keZM.jpg (AMD HWA Enabler ScreenShot)
