### ISSUE TITLE
Bluetooth registry keys function broken on Monterey

### ISSUE THREAD

**Issue by Mahas1** [headkaze/Hackintool#141]
![Screenshot 2021-07-03 at 1 14 13 PM](https://user-images.githubusercontent.com/82939599/124347132-91410400-dc00-11eb-9b1b-3253fa394f16.png)
I'd click on the bluetooth icon in there, it would ask for my password, and boom! Nothing happens. 

It worked fine on Big Sur. I hope this gets resolved soon. If any more more information is needed, please inform me, I'll add it here

**Comment by headkaze** [comment]
Can you please try 3.7.1

**Comment by Mahas1** [comment]
Works now, thank you.
