### ISSUE TITLE
Hackintool shows wrong version of ECEnabler

### ISSUE THREAD

**Issue by yanisalbert** [headkaze/Hackintool#143]
Hi,
i've updated ECEnabler to version 1.0.1 but hackintool still displays V 1 .
<img width="1960" alt="Capture d’écran 2021-07-07 à 12 47 08" src="https://user-images.githubusercontent.com/87071207/124748390-59e59680-df23-11eb-9027-60ad4738e280.png">

**Comment by headkaze** [comment]
Can you please try v3.6.2 and let me know if it's displaying correctly now?

**Comment by yanisalbert** [comment]
Hi, no changes with v3.6.2. May be it is ECEnabler the culprit. ECEnabler infos shows 1.0
<img width="387" alt="Capture d’écran 2021-07-08 à 22 42 20" src="https://user-images.githubusercontent.com/87071207/124988610-817d5180-e03e-11eb-8292-ad576e0c06c7.png">

**Comment by yanisalbert** [comment]
It's ok now with ECEnabler version 1.0.2
