### ISSUE TITLE
Bluetooth Info does not appear in Peripherials

### ISSUE THREAD

**Issue by plucasa** [headkaze/Hackintool#157]
Hi, the Bluetooth information does not appear in the Peripherials information, however it is working normally in my macOS Monterey Hack. Refer screenshot
![Screenshot at Nov 22 18-22-35](https://user-images.githubusercontent.com/89082457/142954471-0d8fdfe3-c88d-40c8-88a4-278bf81f4fd4.png)

**Comment by headkaze** [comment]
What version of Hackintool? If you have the latest please post your .ioreg.

**Comment by plucasa** [comment]
> 

There you go! ioreg attached..
[ioreg.zip](https://github.com/headkaze/Hackintool/files/7585841/ioreg.zip)
..

**Comment by headkaze** [comment]
It doesn't look like you have a Bluetooth device loaded correctly.

Make sure you have BlueToolFixup.kext, BrcmFirmwareData.kext and BrcmPatchRAM3.kext in the Kernel->Add section of your config.plist

[BrcmPatchRAM-2.6.2-RELEASE.zip](https://github.com/headkaze/Hackintool/files/7588939/BrcmPatchRAM-2.6.2-RELEASE.zip)
.

**Comment by plucasa** [comment]
> It doesn't look like you have a Bluetooth device loaded correctly.
> 
> Make sure you have BlueToolFixup.kext, BrcmFirmwareData.kext and BrcmPatchRAM3.kext in the Kernel->Add section of your config.plist as well as copied into your OC/Kexts directory.
> 
> [BrcmPatchRAM-2.6.2-RELEASE.zip](https://github.com/headkaze/Hackintool/files/7588939/BrcmPatchRAM-2.6.2-RELEASE.zip) .

My Wifi Card + Bluetooth does not need these kexts, it is an original iMac card so it is native supported
![Screenshot at Nov 23 11-33-25](https://user-images.githubusercontent.com/89082457/143076259-00836380-0e6f-4dd0-953b-c601bfcd846e.png)
.

**Comment by headkaze** [comment]
So it appears that natively supported cards don't show up as USB devices in IORegistry.

Can you please post the output from this Terminal command:
`system_profiler SPBluetoothDataType -xml`

**Comment by plucasa** [comment]
> So it appears that natively supported cards don't show up as USB devices in IORegistry.
> 
> Can you please post the output from this Terminal command: `system_profiler SPBluetoothDataType -xml`

Attached....
There you go!
[Output.zip](https://github.com/headkaze/Hackintool/files/7590126/Output.zip)

**Comment by headkaze** [comment]
Can you please try 3.7.2

**Comment by mmbdh1** [comment]
Hello everyone, very strange thing. In my case, the information about bluetooth is always there but once my Hack goes into standby then this information disappears afterwards.

**Comment by mmbdh1** [comment]
By the way, I'm already using the last version 3.7.2

**Comment by mmbdh1** [comment]
![Bevor spped:wake](https://user-images.githubusercontent.com/56742487/143125372-96032c67-712c-42d6-9c8d-19d25af90193.jpg)

**Comment by headkaze** [comment]
@mmbdh1 can you please post your .ioreg before and after standby?

**Comment by plucasa** [comment]
> Can you please try 3.7.2

Now it is visible! in Peripherials! i have also tried after sleep and standby and it is still visible. Thanks for your effort!

![Screenshot at Nov 23 16-43-09](https://user-images.githubusercontent.com/89082457/143141009-4e83c6cd-5ea5-4497-8df6-bb6d0fa61ef3.png)
