### ISSUE TITLE
V 3.8.4 Bug : Patch reading bug in Configplist

### ISSUE THREAD

**Issue by Baio1977** [headkaze/Hackintool#168]
This my HW ,
![Schermata 2022-01-16 alle 13 36 35](https://user-images.githubusercontent.com/59058746/149660172-22b552f3-b882-4495-b7b3-d51df45ddb72.png)
the click on the eye works, but when I see the patch in use it doesn't tell the truth
![Schermata 2022-01-16 alle 13 38 09](https://user-images.githubusercontent.com/59058746/149660231-949a9bef-1c4e-452e-9efc-95534b3181d6.png)
actually this is the patch
![Schermata 2022-01-16 alle 13 39 48](https://user-images.githubusercontent.com/59058746/149660283-befa9b41-e2c6-4e0f-af9a-ff752aa88aee.png)

**Comment by headkaze** [comment]
Please post your config.plist

**Comment by Baio1977** [comment]
[Config.plist.zip](https://github.com/headkaze/Hackintool/files/7877408/Config.plist.zip)

**Comment by headkaze** [comment]
Hackintool doesn't apply your patches by default. Are you using File->Open config.plist or are you using Patch->Apply Current Patches so it loads your patches from IORegistry?

**Comment by Baio1977** [comment]
Ok then I apologize, I was expecting too much from Hackintool. I close the issue

**Comment by headkaze** [comment]
> Ok then I apologize, I was expecting too much from Hackintool. I close the issue

It does exactly what you want just not by default. You must use File->Open your config.plist file or Patch->Apply Current Patches to load from IORegistry (currently booted patches)
