### ISSUE TITLE
Bluetooth reg tool doesn't support Bluetooth 5.0 devices

### ISSUE THREAD

**Issue by Ush-J** [headkaze/Hackintool#169]
hackintool ver 3.8.4 
monterey 12.0.1
It seems that bluetooth 5.0 device add keys 'CSRK' 'CSRKInbound' 'InboundSignCounter' 'OutboundSignCounter' 
But I can't find these keys in the file Bluetooth.reg or in the flie /private/var/root/Library/Preferences/com.apple.bluetoothd.plist 
![image](https://user-images.githubusercontent.com/93069140/150056300-d1565216-2bb1-4529-9650-fe9187a3d8f0.png)![image](https://user-images.githubusercontent.com/93069140/150056505-06744bd8-b1bb-419c-a220-04df4be571cd.png)
and I can't find the file com.apple.bluetooth.plist in /Library/Preferences 
Please help
Thanks

**Comment by Ush-J** [comment]
I found the pair message in keychain.
<img width="1392" alt="截屏2022-01-20 13 31 48" src="https://user-images.githubusercontent.com/93069140/150279487-6567e264-794f-4373-b347-25c6f5409258.png">
I hope this will help you.

**Comment by Ush-J** [comment]
> Can you please export the key in your first screenshot from your Windows registry and post it here along with a text file containing the keychain dump. Also please include the Bluetooth.reg file generated by Hackintool.
before fix
![win before fix](https://user-images.githubusercontent.com/93069140/150467937-48f74871-4442-455c-9dde-0288236b7725.png)
mac
<img width="679" alt="mac" src="https://user-images.githubusercontent.com/93069140/150467944-ee9584d0-dd6c-47cd-b323-487f12efb7b0.png">
after fix( I edited the address, from f4ee25e13ab9 to f4ee25e139b9)
<img width="455" alt="win after fix" src="https://user-images.githubusercontent.com/93069140/150467952-2166296b-f794-4b7d-9f45-c5594e03356f.png">
[reg.zip](https://github.com/headkaze/Hackintool/files/7910507/reg.zip)

**Comment by headkaze** [comment]
Can you export the key in your first post (the one that contains 'CSRK' 'CSRKInbound' 'InboundSignCounter' 'OutboundSignCounter') and attach it here.

Can you also attach the output to the command:
`system_profiler -xml -detaillevel full SPBluetoothDataType`

I'm not sure where I can obtain this data from on macOS if it's not in the above files?

**Comment by headkaze** [comment]
Any reason why this was closed? Did you solve the issue?
