### ISSUE TITLE
New Framebuffer Patch for HDMI from Whatevergreen

### ISSUE THREAD

**Issue by williambj1** [headkaze/Hackintool#23]
Hi! @headkaze 
An impressive fix for HDMI was just merged into Whatevergreen

https://github.com/acidanthera/WhateverGreen/pull/24/files#diff-f57337b786936aee0f3bedf3fe5eee07R1668

I believe it will be awesome if Hackintool can generate this fix as well!😀

Thank you very much!

**Comment by headkaze** [comment]
Added in Hackintool v2.6.7 :)

I haven't done any testing though so I'd appreciate any feedback on it.
