### ISSUE TITLE
FakeSMC 'update available' confusion

### ISSUE THREAD

**Issue by exquirentibus** [headkaze/Hackintool#29]
This is probably a misunderstanding on my part, but ... that might help you make Hackintool a better tool for the majority who may have limited comprehension of the correct kexts to use?

As shown in my included image, Hackintool 2.8.0 shows FakeSMC 1800 as installed, but with an 'update available'.

I grabbed FakeSMC from [https://bitbucket.org/RehabMan/os-x-fakesmc-kozlek/downloads/ ](url) and the date is 9/15/18.

I looked at the suggested url of: [https://github.com/RehabMan/OS-X-FakeSMC-kozlek/tree/master/FakeSMC](url) and noticed that the last commit was 6/7/17 - which seems earlier than my version?

 I gather that RehabMan may have been inactive recently, with some of his code forked and modified.  How do I resolve this?  What's the 'correct' kext to use for 10.14.6?

I've thought of switching to VirtualSMC, but Clover still seems to use FakeSMC to determine whether to inject kexts, so I can't tell if that's the way to go?  I suppose it would show in the 'superseder' column at that point?

I love the tool - and have one small feature request.

If you added a checkbox to the 'installed kexts' tab for 'only show installed', this would make it a bit easier to see the 'big picture' quickly.  And a button to output to a text file a list of the installed kext names and their versions would be very useful in documenting version changes to a Hackintosh volume.

Might even pull the kexts to be injected, .aml's, drivers used, etc. from the Clover EFI to a text file?  I spend a lot of time documenting, making Carbon Copy backups, and then making small incremental changes.  This would really help to document that current state of the custom kexts installed in S/L/E and the EFI setup.

![Hackintool FakeSMC](https://user-images.githubusercontent.com/13613918/65391708-f4b2b800-dd31-11e9-8b99-c73618d28a36.png)

**Comment by exquirentibus** [comment]
I'd like to add a few other suggestions to your Great utility:

Show these in 'Installed Kexts':
XHCI-unsupported.kext from https://github.com/RehabMan/OS-X-USB-Inject-All
IntelMausi.kext https://github.com/acidanthera/IntelMausi

And a small cosmetic issue - possibly remember screen size and position?

**Comment by headkaze** [comment]
I believe I added your requests
