### ISSUE TITLE
[Bug] Hackintool will generate a UHD630 when whatever ID is selected

### ISSUE THREAD

**Issue by williambj1** [headkaze/Hackintool#3]
![image](https://user-images.githubusercontent.com/45396585/57117891-f1725c00-6d91-11e9-80cd-d5d9a147052b.png)

PS: I reported this on Tonymacx86 a week ago but I don't know why the Admin deleted it.

**Comment by headkaze** [comment]
The PCI data is pulled from the [pci.ids](https://pci-ids.ucw.cz) project.

**Comment by williambj1** [comment]
A user told me that it shows UHD630 even he has a UHD620

**Comment by headkaze** [comment]
The PCI data is from pci.ids file based on device id. Please check his device id in the pci.ids file.

**Comment by williambj1** [comment]
Sorry for reporting the wrong issue, confirmed that this works well!
