### ISSUE TITLE
Version Checking for OpenCore

### ISSUE THREAD

**Issue by williambj1** [headkaze/Hackintool#35]
@headkaze 

Hi Headkaze, I've just updated to the latest version of Hackintool and I noticed an issue
I'm using a self compiled version of OpenCore which includes the latest changes in master (0.5.2).
The version is displayed correctly but the update checker seems to have some trouble comparing the versions.

![image](https://user-images.githubusercontent.com/45396585/67154541-a690d480-f330-11e9-8204-3e2d1ba656fb.png)

**Comment by headkaze** [comment]
You caught me being lazy! I have added a proper version compare routine so it should be fixed in Hackintool v2.8.3.

**Comment by williambj1** [comment]
Now it works fine :)

Thanks!
