### ISSUE TITLE
Turkish localization issue

### ISSUE THREAD

**Issue by osxinfo** [headkaze/Hackintool#36]
Hey Headkaze
It seems The Turkish localization file had not included in the Hackintool Project Info as one of the default languages.  Therefore, the interface returns to English, when the app automatically updated.
Thanks.
![Ekran Resmi 2019-10-20 11 04 39](https://user-images.githubusercontent.com/23379769/67157223-988b8580-f329-11e9-8769-53f18763885e.png)

**Comment by headkaze** [comment]
Thanks for letting me know. It's been added in the latest commit
