### ISSUE TITLE
2.8.5 quits unexpectedly

### ISSUE THREAD

**Issue by BbIKTOP** [headkaze/Hackintool#40]
Quit when trying to generate patch (on "Generate patch" button press)

[hackintool.quit.report.txt](https://github.com/headkaze/Hackintool/files/3801668/hackintool.quit.report.txt)

**Comment by headkaze** [comment]
Thanks for reporting. Please try the latest release.

**Comment by BbIKTOP** [comment]
Sorry for delay, everything is working so far, thank you
