### ISSUE TITLE
VoodooPS2Controller fails to build from source

### ISSUE THREAD

**Issue by itnok** [headkaze/Hackintool#46]
It looks like #acidanthera adopted a submodule in [VoodooPS2](https://github.com/acidanthera/VoodooPS2) to bring in support for #VoodooInput.
This change is a breaking change for Hackintool which at the current stage does not support repos using submodules: simply cloning the repo is not sufficient anymore and a further step is actually required _(`git submodule update --init --recursive`)_ before starting the build.

**Comment by headkaze** [comment]
Thanks for adding this
