### ISSUE TITLE
New app icon

### ISSUE THREAD

**Issue by ultratiem** [headkaze/Hackintool#48]
![Hackintool](https://user-images.githubusercontent.com/2991193/70210843-8ce0fc00-16e8-11ea-9f54-e5d64f109db4.png)

😁

**Comment by headkaze** [comment]
It looks good but the minimum size needs to be 1024 x 1024

**Comment by ultratiem** [comment]
Attaching the finalized version. Something elegant.

https://dl.dropbox.com/s/u1afgbwxy3t4e2i/HT%20Icon.zip

Happy holidays 🦁

**Comment by headkaze** [comment]
People are liking it, thanks!
