### ISSUE TITLE
Patch -> System Config -> Gigabyte -> Designare Template Confusion

### ISSUE THREAD

**Issue by TheCakeGit** [headkaze/Hackintool#52]
Hi

There are three templates for one motherboard:

Designare Z390 [i9-9900K_ZISQO] 
Designare CFG V1
Designare CFG V2

I don't see anywhere that explains the differences?

Thanks.

**Comment by headkaze** [comment]
The patches come from [here](https://www.tonymacx86.com/threads/guide-general-framebuffer-patching-guide-hdmi-black-screen-problem.269149)
