### ISSUE TITLE
PCI tab crashing on newest version, 2.9.4

### ISSUE THREAD

**Issue by Deep0d0** [headkaze/Hackintool#56]
Hello, just updated from version 2.8.6, and now the PCI Tab is crashing. Tested across two Hackintoshes.

I suspect it has something to do with the new addition of the aspm tab.

attaching behavior and [crash log](https://pastebin.com/1Cq6nWnu)
[Untitled.mov.zip](https://github.com/headkaze/Hackintool/files/4125042/Untitled.mov.zip)

**Comment by headkaze** [comment]
Can you please try 2.9.5

**Comment by Deep0d0** [comment]
working great, thanks!

**Comment by headkaze** [comment]
The issue was an ASPM value in your IORegistry was in NSData format but I expect it to be in NSNumber format. I now convert the NSData to NSNumber but I want to make sure it's working okay. Can you please zip/attach your ioreg (run "ioreg -l >~/ioreg.txt" from Terminal)

**Comment by Deep0d0** [comment]
[ioreg.txt](https://github.com/headkaze/Hackintool/files/4125777/ioreg.txt)

**Comment by headkaze** [comment]
Thanks!
