### ISSUE TITLE
USB port patching creating phantom entries

### ISSUE THREAD

**Issue by ultratiem** [headkaze/Hackintool#59]
1. Load USB tab.
2. Delete all ports but one (doesn't matter which here)
3. Export.
4. Import.

I'm seeing duplicate entries, the correct one and one missing the location ID.

In fact, the import button doesn't seem to replace all the current entries. It should (and maybe I'm remembering wrong, but did in previous versions?).

I suggest adding another button if you want to append an existing file with the current list.

**Comment by headkaze** [comment]
Should be fixed in v3.1.9

**Comment by ultratiem** [comment]
Cheers.

Still seems to be pulling the wrong ports tho. I'll upload my kext file. When I import, it's listing ports that do not exist.

<img width="589" alt="Screen Shot 2020-02-23 at 4 01 40 PM" src="https://user-images.githubusercontent.com/2991193/75122766-fae8ef80-5655-11ea-9cd2-84229e626557.png">

[USBPorts.kext.zip](https://github.com/headkaze/Hackintool/files/4242756/USBPorts.kext.zip)

**Comment by headkaze** [comment]
Can you please post your .ioreg

**Comment by ultratiem** [comment]
[Galvatron.ioreg.zip](https://github.com/headkaze/Hackintool/files/4243047/Galvatron.ioreg.zip)

**Comment by mackonsti** [comment]
Hi @ultratiem I had a similar issue and recently _Hackintool_ now exports the values well as the **Location ID** seems to matter most. I also have twin entries but as **Location ID** is different, the system treats them differently. I believe you'd be OK with the latest _Hackintool_ (today at v3.3.7).
