### ISSUE TITLE
Missing Report 1

### ISSUE THREAD

**Issue by williambj1** [headkaze/Hackintool#6]
![image](https://user-images.githubusercontent.com/45396585/57172335-04983100-6e51-11e9-8f7f-48aaacdc75cf.png)
![image](https://user-images.githubusercontent.com/45396585/57172567-78880880-6e54-11e9-9c3e-219606177804.png)
![image](https://user-images.githubusercontent.com/45396585/57172577-9190b980-6e54-11e9-84b9-a912e2485578.png)
![image](https://user-images.githubusercontent.com/45396585/57172583-aa00d400-6e54-11e9-8717-f5eace730f4e.png)
![image](https://user-images.githubusercontent.com/45396585/57172599-d3216480-6e54-11e9-8c42-3ab64485cd80.png)
![image](https://user-images.githubusercontent.com/45396585/57172614-fd732200-6e54-11e9-8ecd-145e248b3a68.png)
![image](https://user-images.githubusercontent.com/45396585/57172638-24c9ef00-6e55-11e9-8f2c-28b44f315415.png)
![image](https://user-images.githubusercontent.com/45396585/57172642-34493800-6e55-11e9-8b6b-32727dbfc8fa.png)
![image](https://user-images.githubusercontent.com/45396585/57172650-4fb44300-6e55-11e9-8bc7-19211f4e1c01.png)
![image](https://user-images.githubusercontent.com/45396585/57172657-6bb7e480-6e55-11e9-82a6-050473cb2075.png)

**Comment by headkaze** [comment]
I've added the entries listed above.

**Comment by williambj1** [comment]
Thanks!
