### ISSUE TITLE
Localizable.strings out of sync

### ISSUE THREAD

**Issue by williambj1** [headkaze/Hackintool#63]
HI @headkaze ,

I really enjoy the new UI, however, the localization files are out of sync right now and plenty of the strings are broken, could you please fix it? Thanks a lot!

Have a nice day!

![image](https://user-images.githubusercontent.com/45396585/75318934-94a6db80-58a6-11ea-8af6-4dcaed802913.png)

**Comment by qin9125** [comment]
thank you

**Comment by headkaze** [comment]
I just need to get a list of changes from @ultratiem and will let you know as soon as I update the localization files.

**Comment by williambj1** [comment]
Thanks, really appreciate your work!

**Comment by ultratiem** [comment]
@headkaze just pushed a fixed for the Chinese simplified strings. I'll go thru the rest, no time right now.

@williambj1 there is no Chinese for "USB" ;) (you also missed "Serial")

**Comment by qin9125** [comment]
> 我只需要从@ultratiem获取更改列表，并在更新本地化文件后立即通知您。

![6592EB9247CFFBB0BCD21AEB742B317B](https://user-images.githubusercontent.com/32502941/75335860-21f92880-58c5-11ea-850f-de25a237706f.jpg)

**Comment by williambj1** [comment]
@ultratiem 

Oh, "USB" was actually a mistake, didn't ment to translate it, I accidentally labeled, sorry for that, totally my fault.

Thanks for your nice UI design. Looks fresh!

**Comment by headkaze** [comment]
@headkaze there were quite a few missing from your update but I've gone through and got most of them (all languages)

**Comment by williambj1** [comment]
@headkaze 

So the localization files in the latest commit bd48781184ad876a3d9bf3f1744c50eb3229aaff is good to go?

**Comment by headkaze** [comment]
Yes so you can go ahead and do the translation and let me know if I've missed anything and I can go through and add them to another commit. I just like to keep all the translation files in the same order so they're easier to manage.

@ultratiem In Xcode you can click on the Hackintool target at the top and select Edit Scheme... then under Options->Application Language select Korean from the drop down list. Now you can run Hackintool in Korean to check the translations. It's really easy to miss them without using this function.

**Comment by williambj1** [comment]
The following strings are still out of sync

```swift
"System Info:" // Extra ':' should be "System Info"
"Serial Info" // Present in Korean but not in other languages
"iMessage Keys" // Doesn't localize, I can't find any errors, hmmm
"Internal" // Doesn't localize, no idea.
// Extensions
"Only Show Installed Extensions" // Missing
// Displays
"Scaled Resolutions:" // Extra ':'
// Audio
"Audio Info:" // Extra ':'
// Disks
"Partition Scheme:" // Extra ':'
// Calculator
"Sequence:"  // Extra ':'
“Value:” // Extra ':'
```

ref for "Internal"

![image](https://user-images.githubusercontent.com/45396585/75364343-8bddf600-58f6-11ea-9eb6-d2e91790b824.png)

btw, those texts blur quite a lot.

![image](https://user-images.githubusercontent.com/45396585/75364462-bdef5800-58f6-11ea-8621-435f01178a34.png)

**Comment by ultratiem** [comment]
@williambj1 thanks again for the reports. But please file each problem separately. The text being blurred has nothing to do with Hackintool (I cannot reproduce this).

I have fixed the remaining locales so we should be back up to parity from before I started meddling. I'll continue to sift thru it and fix things as I find them.

@headkaze thanks for the tip (and going in and fixing most of this). I was using Language & Region settings to set the language for the app directly. I've pushed a few commits to fix the last remaining issues.

This will be a WIP. I'll try to go thru and clean all this up and flesh out each translation as best I can going forward.

**Comment by headkaze** [comment]
I think we're ready for translation updates now

**Comment by williambj1** [comment]
![image](https://user-images.githubusercontent.com/45396585/75624949-584fe400-5bf4-11ea-9cff-90b6b08391cc.png)

Few new strings missing

**Comment by headkaze** [comment]
Okay just did an update adding the missing strings

**Comment by headkaze** [comment]
I should probably add the other strings like "In", "Out", "Fixed", "Jack" etc.

**Comment by williambj1** [comment]
Thanks, I'll wait for your update for `in`, `out`, etc.

**Comment by headkaze** [comment]
Okay done

**Comment by williambj1** [comment]
![image](https://user-images.githubusercontent.com/45396585/75626990-36139180-5c07-11ea-947e-394e7a8e1abd.png)

In/Out is still missing.

in = "输入"
out = "输出"

Thanks for your hard work!

**Comment by headkaze** [comment]
Changes commit, thanks!

**Comment by williambj1** [comment]
:)
