### ISSUE TITLE
Broken updater download count

### ISSUE THREAD

**Issue by williambj1** [headkaze/Hackintool#64]
![image](https://user-images.githubusercontent.com/45396585/75361519-618a3980-58f2-11ea-8d54-8da3914aa4a7.png)

I originally thought this was an issue of my macOS which has been used for quite a long time, but after I reinstalled the system today, the bug is still there.

I'm not sure whether it is a change of sending packages from the server (downloading source code as zip on GitHub produces a similar progress bar in Google Chrome) or it's a bug of the app's UI.

Thanks again for your awesome work!

**Comment by ultratiem** [comment]
What exactly is broken about this screen?

**Comment by williambj1** [comment]
@ultratiem 

First of all, this issue is not related to your new UI, it has been there for several versions.

The updater used to show **`downloaded` of `total`** correctly but now it shows **`downloaded` of `downloaded`** and the progress bar is always full.

**Comment by ultratiem** [comment]
Oh, by the look of the progress bar it looked at 100% (and technically I suppose it is).

You are correct in your first post: this is a byproduct of how the files are pulled. An async spinner would be better suited in this case if time to completion is unknown. That can be represented visually with just having the download count from the current implementation. Ideally, having fallbacks to account for these things would be the way to go.

Then I could focus on one, nice UI for this screen.

**Comment by williambj1** [comment]
Thanks for your explanation and your hard work!

**Comment by headkaze** [comment]
Some servers don't supply the total size for a file download.
