### ISSUE TITLE
Stuck Clover Boot Loader Window

### ISSUE THREAD

**Issue by ultratiem** [headkaze/Hackintool#65]
Steps to reproduce:

1. Go to Boot tab
2. Select Clover and let Hackintool list an update
3. Select Update
4. When the Save dialogue prompt appears, select cancel

A secondary Clover update window emerges but hitting cancel does not dismiss it.

<img width="660" alt="Screen Shot 2020-02-26 at 10 26 29 AM" src="https://user-images.githubusercontent.com/2991193/75375204-76c77f80-5882-11ea-90c7-6692f98bf005.png">

**Comment by headkaze** [comment]
This should be fixed in the next release
