### ISSUE TITLE
[Solved]New Hackintool have a Bug

### ISSUE THREAD

**Issue by KaoS-TR** [headkaze/Hackintool#73]
Old Hackintool (2.8.6) auto detect a sound codec but new Hackintool (3.2.7) not detect sound codec. Please fix it.
![Ekran Resmi 2020-03-15 06 31 31](https://user-images.githubusercontent.com/61596341/76694694-165c7e80-6687-11ea-8b32-563fb53aafab.png)

**Comment by headkaze** [comment]
After opening Hackintool and selecting the Audio tab please run "log show --predicate 'process == "Hackintool"' --style syslog --source --last boot >~/Hackintool.log" from Terminal.

Can you then attach your your ioreg and Hackintool log here.

**Comment by KaoS-TR** [comment]
Thank you for answering my problem quickly.
The files you want are attached.
[Hackintool old.log](https://github.com/headkaze/Hackintool/files/4334667/Hackintool.old.log)
[Hackintool.log](https://github.com/headkaze/Hackintool/files/4334669/Hackintool.log)
[KaoS MacBook Pro.zip](https://github.com/headkaze/Hackintool/files/4334670/KaoS.MacBook.Pro.zip)

**Comment by headkaze** [comment]
Hackintool enumerates all audio devices matching the class IOAudioDevice and I can't see why your device isn't being listed. There doesn't appear to be any exception or error in your log either. Did you click on the Audio tab before generating the log so it will capture the error?

**Comment by KaoS-TR** [comment]
I am created a log files in old and new hackintool open and click to audio tab.
I can record video if you want.

**Comment by KaoS-TR** [comment]
This error is not unique to this device or to me. Sound card is not shown on the new hackintool in all our members in our forum.
But if we introduce the sound card, it sees the new hackintool.

**Comment by KaoS-TR** [comment]
I am recording video
Fresh start Computer and Old Hackintool Log Video
https://yadi.sk/i/6Yq9YikX802cmA
Then Restart Computer and New Hackintool Log Video
https://yadi.sk/i/mTdiG_WfqwwcbQ
Then Activate my Sound Card
https://yadi.sk/i/ogd5EcMhK12aPQ
Then restart Computer and New Hackintool Autio Tab
https://yadi.sk/i/rZwwbqgxVPuBMA
[Hackintool.log](https://github.com/headkaze/Hackintool/files/4334838/Hackintool.log)
[Hackintool old.log](https://github.com/headkaze/Hackintool/files/4334839/Hackintool.old.log)
[KaoS MacBook Pro.zip](https://github.com/headkaze/Hackintool/files/4334841/KaoS.MacBook.Pro.zip)

**Comment by headkaze** [comment]
Can you send me your ioreg before you activate your sound card.

**Comment by KaoS-TR** [comment]
Active sound and new Hackintool log and Ioreg Video
https://yadi.sk/i/SpL79XM_t-8dmQ
[KaoS MacBook Pro.zip](https://github.com/headkaze/Hackintool/files/4335027/KaoS.MacBook.Pro.zip)
[Hackintool.log](https://github.com/headkaze/Hackintool/files/4335028/Hackintool.log)

**Comment by headkaze** [comment]
Can you please perform the same procedure to get the Hackintool.log for this version (Hackintool_Test.zip]([https://headsoft.com.au/download/mac/Hackintool_Test.zip). I've added some extra debug output. No video is necessary.

**Comment by KaoS-TR** [comment]
I'm sorry for the late reply. The files you want are attached.
[Hackintool Working Audio.log](https://github.com/headkaze/Hackintool/files/4338586/Hackintool.Working.Audio.log)
[Hackintool.log](https://github.com/headkaze/Hackintool/files/4338587/Hackintool.log)

**Comment by headkaze** [comment]
I really can't see why it's not enumerating your audio devices even with the extra debug output. All it's telling me is it can't find any device that's an "IOAudioDevice" yet looking at your ioreg dump it's clearly there.

Perhaps you could clarify what you mean by "introduce the sound card"? Do you have AppleALC.kext installed both times?
<img width="780" alt="IOAudioDevice01" src="https://user-images.githubusercontent.com/1698401/76768900-ebdaf600-6758-11ea-93ce-19f246aa259d.png">
<img width="780" alt="IOAudioDevice02" src="https://user-images.githubusercontent.com/1698401/76768910-ef6e7d00-6758-11ea-8b6f-14c8f6240b15.png">

**Comment by KaoS-TR** [comment]
This system fresh install. AppleALC.kext is E/C/K/O. I am not manual kext install S/L/E or L/E.
Older Hackintool not problem.
We have Turkish Hackintosh Forum and forum users have a auido problem time we says open Hackintool and go to sound tab but new Hackintool not output for all users.
I say is old Hackintool open go to sound tab. 
What is change old and new Hackintool ?

**Comment by KaoS-TR** [comment]
The old hackintool gives voice codec information to all users, why the new hackintool cannot provide this information.
As I said before, this is not something specific to my device. The same is true for all devices.

**Comment by headkaze** [comment]
The only thing I can think of is IOObjectGetClass() is failing for some reason.

Can you please try [Hackintool_Test.zip](https://headsoft.com.au/download/mac/Hackintool_Test.zip). I've removed this and instead read the IOClass value.

**Comment by KaoS-TR** [comment]
I'm try but not change no sound output.
![Ekran Resmi 2020-03-16 18 39 41](https://user-images.githubusercontent.com/61596341/76775344-48203300-67b6-11ea-927b-bb6f28fc9b78.png)
[Hackintool.log](https://github.com/headkaze/Hackintool/files/4338990/Hackintool.log)

**Comment by headkaze** [comment]
I can recreate the issue by removing my layout id in Clover's config.plist. Notice in my screenshots I posted there is no tick next to "Registered" for the non-working IORegistry?

According to Apple documentation IOServiceGetMatchingServices "is the preferred method of finding IOService objects currently **registered** by IOKit (that is, objects that have had their registerService() methods invoked). To find IOService objects that aren't yet registered, use an iterator as created by IORegistryEntryCreateIterator()."

So I need to change to use IORegistryEntryCreateIterator. I'll let you know when I have a working update. Thanks for reporting the issue!

**Comment by KaoS-TR** [comment]
Your welcome.

**Comment by headkaze** [comment]
Please check out 3.2.9

**Comment by KaoS-TR** [comment]
Yes I am tested and perfect thank you.
