### ISSUE TITLE
Disk initialized by Windows not listed by Hackintool

### ISSUE THREAD

**Issue by SkipG** [headkaze/Hackintool#77]
Disk is partitioned with a small EFI partition and large NTFS partition. It is recognized by Diskutil

/dev/disk0 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                  *1.0 TB     disk0
   1:       Microsoft Reserved                        16.8 MB    disk0s1
   2:      Microsoft Basic Data Projects         1.0 TB     disk0s2

Priority is -10

**Comment by headkaze** [comment]
Is it shown in Hackintool? Can you take a screenshot?

**Comment by SkipG** [comment]
It’s not shown in Hackintool in the top window, but is in the detailed list. it’s disk2. So it’s not as bad as I reported, for which I apologize.

Skip

**Comment by headkaze** [comment]
Is it an EFI parition because it should be in the top list if it is?

**Comment by SkipG** [comment]
Yes, the details are correct in the bottom part of the list. I also have an SSD where the EFI partition is second on the disk, and that disk is detected and displayed. Normally the EFI partition is 200 MB if macOS partitions it.

**Comment by SkipG** [comment]
on the list, it shows up as Microsoft Reserved.

**Comment by headkaze** [comment]
How did you create your EFI partition? To be identified as EFI in Hackintool the media content UUID needs to be "C12A7328-F81F-11D2-BA4B-00A0C93EC93B". Microsoft Reserved is "E3C9E316-0B5C-4DB8-817D-F92DF00215AE".

You can use diskpart in Windows with the following command to create an EFI parition:
```
create partition efi size=200
format quick fs=fat32 label="System"
```

**Comment by SkipG** [comment]
diskpart
list disk
sel disk N
clean
convert gpt
create part primary
format fs=ntfs quick label=Projects
exit

convert gpt  creates a small partition which the BIOS interprets as being an AHCI disk
if I then do create part efi it creates the partition as the second partition on the disk.

Disk 1 was created by windows and the EFI partition is partition 2
Disk 2 is not a bootable disk, so I don’t need a large EFI partition.

I have another disk I can play with. I’ll try leaving out the convert gpt and see if your suggestion works.
It isn’t a biggie; I was just surprised that the list didn’t agree with diskutil. 
You have an excellent program; Nuke #77 and I’ll refile if I can't find a solution that keeps Windows happy, macOS happy and Hackintool happy.

Thanks,
Skip

**Comment by headkaze** [comment]
I dual boot Windows and macOS and this is how I created my partitions:
```
1. Run Windows Setup
2. Press Shift+F10 for Command Prompt
3. Run 'diskpart'
4. Run the following commands:
list disk
select disk #
clean
convert gpt
5. Create UEFI system partition (ESP). Type the following:
create partition efi size=200
format quick fs=fat32 label="System"
6. Create MSR partition. Type the following:
create partition msr size=128
7. Exit diskpart and select the empty partition and select New
8. Reboot into macOS
9. Run Disk Utility
10. Split the partition in half
11. Install macOS in the first partition
12. Install Windows 10 in the second partition
```

**Comment by SkipG** [comment]
Thanks, I’ll try that.  I converted GPT, added 200MB EFI partition and a primary NTFS partition. Works fine.

I also partitioned the disk in macOS: diskutil formatDisk diskN 1 gpt exfat <label> 100%; then used disport in Windows to formatthe partition as NTFS.

Just another way of skinning the cat. Thank you for setting me on the right path.
