### ISSUE TITLE
hi headkake! zisqo's bring it up the new ko-kr translation files.

### ISSUE THREAD

**Issue by ZISQO** [headkaze/Hackintool#9]
hi how are ya brother~ it's me zisqo  
btw i bring the new ko-kr file for korean users but i have no idea of how can i edit the text in the balloon help area.

but i put it down here without that.
(localization file and i9-9900K headless setting with Z390 DESIGNARE MB: totally 2 files of)

thank you for ya service and have fun!

https://drive.google.com/open?id=1Uiyq1zX7KWkaGGR5LSZno8oVX5O_elFl

**Comment by headkaze** [comment]
Hey thanks zisqo :)

I've updated the ko-kr Localizable.strings file and also added the ToolTip text if you want to add it.

**Comment by ZISQO** [comment]
thank you headkaze!! i've sent a i9-9900K headless config.plist such a Z390 Designare type could you please update for us? : )
i just look forward that it of~ hahahah 
 
anyhow i will merge that after translation again asap for you and us! cheers!
 
-----Original Message-----

**Comment by williambj1** [comment]
@ZISQO 
Hi!
I think there's a small issue with your translation. I suppose you forked from my out-of-date branch and this may cause conflicts, perhaps it's better to fork it from the main branch here. 😯

**Comment by headkaze** [comment]
@williambj1 what makes you think he forked from your branch?

**Comment by ZISQO** [comment]
@williambj1 
HI willambj1!! at the moment that was my mistake and i should be sorry about it then i've delete that respository : )

**Comment by williambj1** [comment]
> @williambj1 what makes you think he forked from your branch?

There is a notification from GitHub and I double checked it via `Insights` -> `Network`. Anyway, glad that it's solved now.😊
