### ISSUE TITLE
Big Sur

### ISSUE THREAD

**Issue by dehjomz** [headkaze/Hackintool#94]
Hi, 
I love Hackintool, it provides valuable information.  While the tool works well on macOS Catalina, the gui interface is however broken at the moment on Big Sur macOS 11.0 beta.  The gui interface on Big Sur doesn't show the icons.  For example, to get USB information, on Catalina, there is a USB icon/button to click on.  On Big Sur, the current version doesn't show the USB icon (although it is still possible to get to the USB menu).  

Take a look.

**Comment by Roolon** [comment]
Same problem. GUI totally destroyed.
![GUI_Problem](https://user-images.githubusercontent.com/22008525/86358066-8105ea00-bc77-11ea-9133-9cd334d38cfe.png)

**Comment by headkaze** [comment]
Should be fixed now

**Comment by dehjomz** [comment]
It's fixed since 3.4.1! It works beautifully in Big Sur, salute!!  Thank you.
